### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by jnus** [ps-developers-sandbox/anchor-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by jnus** [comment]
👋 world

**Comment by ChristianZitzmann** [comment]
Good morning

**Comment by MihaiDiaconitaVitesco** [comment]
Morning

**Comment by CiocoiuRadu** [comment]
Hello!

**Comment by 02de16e2** [comment]
Hi there.

**Comment by BoHaVT** [comment]
Hi

**Comment by AlexTdc** [comment]
Hi !

**Comment by VT-Angela** [comment]
HI!

**Comment by MihaiFoscari** [comment]
Hi!

**Comment by uid03101** [comment]
Just wanna smoke something, now I need to type something... :(

**Comment by Ned-Li** [comment]
only basic experience on Git, want to know more about advanced features.

**Comment by cristiVT** [comment]
Hello

**Comment by IonutMistreanu10** [comment]
Hi there (wave)

**Comment by danielmindru** [comment]
hi

**Comment by OlsaPetr** [comment]
Hello
